### ISSUE TITLE
Mon Issuesusue

### ISSUE THREAD

**Issue by Mathieuu** [Mathieuu/RailsSampleAppW#1]
Test

**Comment by Mathieuu** [comment]
First comment

**Comment by Mathieuu** [comment]
Would it work ? I do not know

**Comment by Mathieuu** [comment]
Third comment

**Comment by Mathieuu** [comment]
I leave my first popup comment !

**Comment by Mathieuu** [comment]
![honey_badger](https://cloud.githubusercontent.com/assets/5503512/7467383/7923155a-f2ac-11e4-9d8f-ccff057dd784.jpg)

**Comment by Mathieuu** [comment]
Essai

**Comment by geoffrey** [comment]
Hello

**Comment by geoffrey** [comment]
HEYYYY

**Comment by geoffrey** [comment]
RESPOND TO ME

**Comment by geoffrey** [comment]
I KNOW YOU CAN SEE ME

**Comment by geoffrey** [comment]
IGNORING ME ??

**Comment by geoffrey** [comment]
Im sad .... :-1:

**Comment by Mathieuu** [comment]
I leave a comment !

### And it seems to work perfecty

**Comment by Mathieuu** [comment]
It works well now

**Comment by geoffrey** [comment]
Hello

**Comment by pnavarrc** [comment]
Updating this issue!
