### ISSUE TITLE
Merge Issue 1

### ISSUE THREAD

**Issue by Mathieuu** [Mathieuu/RailsSampleAppW#4]

**Comment by Mathieuu** [comment]
I think it works doesn't it ?

**Comment by geoffrey** [comment]
Hello

**Comment by Mathieuu** [comment]
![honey_badger](https://cloud.githubusercontent.com/assets/5503512/7465191/101fd3f2-f281-11e4-8097-6757e7c74f21.jpg)

**Comment by Mathieuu** [comment]
New comment edited in fullscreen

**Comment by Mathieuu** [comment]
New comment is here

**Comment by Mathieuu** [comment]
New new comment

**Comment by Mathieuu** [comment]
[package.json | uploaded via ZenHub](http://127.0.0.1:3030/files/5556641db97cd2c18ab9999e)
